### ISSUE TITLE
Could you add....

### ISSUE THREAD

**Issue by snook89** [Trombov/FutureNNAimbot#1]
Hey. Good job u has done here! Could you add all the files(cfg etc) we need to run the bot ?

**Comment by Trombov** [comment]
I can't upload it to github. They have >100mb size.
I'm upload config files in release version. Download it:)

**Comment by snook89** [comment]
I meant just cfg and file u need for the first run! I couldn't even run in in the beginning, than I watched your YouTube video and C&P the config.json it let me run the program but after I put T,CT and hit enter program crash. insert doesn't work in game even if I didn't press enter in dos window :\ so I guess we need some more files ?!

**Comment by Trombov** [comment]
Download release version and copy that files to debug folder please.
