### ISSUE TITLE
Yolo GPU DLL not found

### ISSUE THREAD

**Issue by microsoftv** [Trombov/FutureNNAimbot#2]
I'm running through debug in VS after training and filling up the trainfiles folder. I have the x64 folder in the same folder as the exe. yolo_cpp_dll_gpu.dll is in the x64 folder, but it isn't being found when running the exe.

**Comment by Trombov** [comment]
Altryos is not my project. 

https://github.com/AlturosDestinations/Alturos.Yolo/issues/6

Maybe this will help
https://github.com/AlturosDestinations/Alturos.Yolo/issues/9

Microsoft Visual C++ 2017 Resdistributable (x64)

**Comment by Trombov** [comment]
Solution: Unistall CUDA 10.1 and make sure that you install CUDA 10.0
