### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by snook89** [Trombov/FutureNNAimbot#3]
I have GTX 1080TI 11Gb and after I made around 25 pic's I pressed END and got this 
https://image.prntscr.com/image/eaKilHLqSgWgHzD3AjfSMQ.png

Says Im out of memory?!

**Comment by snook89** [comment]
so I tested if you hit END than close csgo right after program working well. Because csgo use about 50% of GPU and than training process use around 30-45%. so if u didn't leave\close csgo right away u running out of GPU memory!!!
P.S. Maybe add script or code to the main, when u hit END it's close game right after!

**Comment by Trombov** [comment]
Thank you!
I will add it today

**Comment by Trombov** [comment]
Updated.
