### ISSUE TITLE
Capturing screenshots doesn't work correctly

### ISSUE THREAD

**Issue by Neakita** [Trombov/FutureNNAimbot#36]
![Paladins2619229](https://user-images.githubusercontent.com/68691636/88379346-35e57f80-cdbc-11ea-9bd3-58bab323447b.png)
![Discord0840001](https://user-images.githubusercontent.com/68691636/88379658-cae87880-cdbc-11ea-8e03-65179dc66964.png)

All screenshots taken in the game, the same type of filled in black(the game is in full-screen borderless mode, and it doesn't work in window mode either), I tried to take screenshots outside the game, choosing as the game Discord, screenshots regardless of the location of the area were from the upper-left corner.

**Comment by Neakita** [comment]
Performance depends on the mode in which the capture is made, you need to transfer the screenshot to the "centered" mode by pressing numpad9, otherwise it will not work.

**Comment by REKTgg** [comment]
> Performance depends on the mode in which the capture is made, you need to transfer the screenshot to the "centered" mode by pressing numpad9, otherwise it will not work.

i have the same issue as you, but i cant fix it with what you said to do. by default the mode is already on "centered" mode, but it does not work. i get black boxes like you. I found that when making my game a smaller resolution and moved it to the center of the screen it will see the game but still not where the boxes appear to be.

**Comment by dill0511** [comment]
I have this issue as well
