### ISSUE TITLE
Doesn't work with DX11/12 games

### ISSUE THREAD

**Issue by davidacampos** [Trombov/FutureNNAimbot#38]
Because of the API used to get the screenshots (i.e. BitBlt) no longer works with DX11/12 there is no way to train or use the trained. That mentioned API doesn't fail, but returns a black screen instead. Using SharpDX instead might be a possible workaround...

**Comment by davidacampos** [comment]
All right, after further investigation it does work with DX11/12 games BUT it needs to be run in windowed mode, otherwise it's a black screen.

**Comment by Sehyo** [comment]
Hard to get fullscreen pics of the game without injecting and hooking the DirectX API.
