### ISSUE TITLE
Combining models

### ISSUE THREAD

**Issue by Stavtastic** [Trombov/FutureNNAimbot#4]
Is it possible to combine different models? If so how?

And by seperating the objects, does that make the scanning any different or does it interprets the whole model as targets?

Another question, is it possible to not shoot at the head but at the body or center of the model?

**Comment by Trombov** [comment]
1. U can combine model using same objects for it
2. Every model that you scan  with object class become for one object
3. In the new release u can choice it

**Comment by Stavtastic** [comment]
But how do I combine the models? Which steps do I have to take
?

**Comment by Trombov** [comment]
Just use same "object" for the models that mean that object.
For example, T object -> All terrorist on the map/game.
