### ISSUE TITLE
Screenshot button not working

### ISSUE THREAD

**Issue by Stavtastic** [Trombov/FutureNNAimbot#7]
I've downloaded the hotfix for the screenshot button, but this is not working for me.

**Comment by Trombov** [comment]
This fix for ScreenshotModeKey. Not for ScreenshotKey. 
Anyway, change the ScreenshotKey value and it will be work

**Comment by microsoftv** [comment]
The screenshotkey is set to home.

**Comment by justspeedx** [comment]
how to change the screenshot key?

**Comment by microsoftv** [comment]
Delete your config.json, reopen the exe, close exe, open config, change key to number from looking at code. Search for “Keys” in this github for the ids.
